### ISSUE TITLE
Pure PHP Version?

### ISSUE THREAD

**Issue by unwarysheep** [igorw/reasoned-php#2]
Is there likely to a pure-php version of this codebase which doesn't require HHVM? I am asking because HHVM isn't a standard-affair install with web hosts and my dev environment is on Mac OS X. I'm trying to keep my dev environment as 'pure' as possible to allow for greater compatibility.

**Comment by igorw** [comment]
The core system works without HHVM. It's mostly the oleg numbers that were implemented with HHVM closure syntax. I don't really have much interest in porting them over, because frankly, closures in "pure" PHP are a nightmare and make the code even less readable.

You can just include `reasoned.php` and toy with that. I am going to remove oleg numbers from the default autoload.

**Comment by igorw** [comment]
EDIT: Also please note that this project is still highly unstable. There are still some significant bugs (see bottom of `test.php` for edge cases that are diverging). That said, most cases _are_ working and playing around with them is definitely fun! ;-)
